In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("preprocessExample (1).csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    9 non-null      object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [5]:
data.head()

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes


In [6]:
#Create a model that can predict if the customer will make a purchase in my ecom
#website based on customer's age, estimated salary and location.
#
# Supervised Leanring problem
# Features: Country, Age, Salary
# Label: Purchased (Categorical) | Classification Problem
#
# Model Building (Inferential Stats) | Prepare your data
# =======================================================
#
# 1. Data must be COMPLETE
# 2. Data must be STRICTLY NUMERIC

In [7]:
# Whenever you are working on sklearn classes, ensure your data is represented in the form of
# numpy array

In [8]:
#Step1: Seperate data as features and label

features = data.iloc[:,[0,1,2]].values
label = data.iloc[:,[3]].values


In [9]:
features


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       [nan, 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
label

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [11]:
# Handling Missing Value ----- Imputation
features[:,[0]]

array([['France'],
       ['Spain'],
       ['Germany'],
       ['Spain'],
       ['Germany'],
       ['France'],
       ['Spain'],
       ['France'],
       [nan],
       ['France']], dtype=object)

In [12]:
#Step1: Import relevant library

from sklearn.impute import SimpleImputer

#Step2: Instantiate the SimpleImputer Object

siForCountry = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

#Step3: Fit the data to the object (Internally it will calc the mode of the country column)

siForCountry.fit(features[:,[0]])

#Step4: Transform the data ---> In this case, transform means replace nan with the mode value calc above
features[:,[0]] = siForCountry.transform(features[:,[0]])

In [13]:
features

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['France', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
# Age --- median
#Step1: Import relevant library

from sklearn.impute import SimpleImputer

#Step2: Instantiate the SimpleImputer Object

siForAge = SimpleImputer(missing_values=np.nan, strategy='median')

#Step3: Fit the data to the object (Internally it will calc the mode of the country column)

siForAge.fit(features[:,[1]])

#Step4: Transform the data ---> In this case, transform means replace nan with the mode value calc above
features[:,[1]] = siForAge.transform(features[:,[1]])

In [15]:
features

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['France', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [16]:
# Salary ---- mean
#Step1: Import relevant library

from sklearn.impute import SimpleImputer

#Step2: Instantiate the SimpleImputer Object

siForSalary = SimpleImputer(missing_values=np.nan, strategy='mean')

#Step3: Fit the data to the object (Internally it will calc the mode of the country column)

siForSalary.fit(features[:,[2]])

#Step4: Transform the data ---> In this case, transform means replace nan with the mode value calc above
features[:,[2]] = siForSalary.transform(features[:,[2]])

In [17]:
features

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['France', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [18]:
# Sklearn also performs OHE using  OneHotEncoder class

In [19]:
from sklearn.preprocessing import OneHotEncoder

oheForCountry = OneHotEncoder(sparse_output=False)

oheForCountry.fit(features[:,[0]]) #This will do the same OHE Process (Extract unique values and sort in asc order)


countryDummyVariable = oheForCountry.transform(features[:,[0]]) #Create Dummy Variables

In [20]:
countryDummyVariable

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [21]:
oheForCountry.categories_

[array(['France', 'Germany', 'Spain'], dtype=object)]

In [22]:
# Transform categorical to dummy

oheForCountry.transform(np.array(["Germany"]).reshape(-1,1))

array([[0., 1., 0.]])

In [23]:
# Transform dummy to categorical

oheForCountry.inverse_transform(np.array([[0., 0., 1.]]))

array([['Spain']], dtype=object)

In [24]:
finalFeatures = np.concatenate((countryDummyVariable, features[:,[1,2]]), axis=1) #axis = 1 means column concat
finalFeatures

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)